[package]
name = "rustlabels"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustlabels"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.0"
axis_labels_rs = "0.2.0"
